// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABE_XNzPxTo5EHF_v5QUwJBVLdkFRdW6w',
    appId: '1:266265608256:web:c7e3c4e999e999138f5fa5',
    messagingSenderId: '266265608256',
    projectId: 'food-app-delivery-5d273',
    authDomain: 'food-app-delivery-5d273.firebaseapp.com',
    storageBucket: 'food-app-delivery-5d273.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdMx8OT-J2fyAffVbqptIvtsG2Wqmp5M4',
    appId: '1:266265608256:android:b6e457db367fec5b8f5fa5',
    messagingSenderId: '266265608256',
    projectId: 'food-app-delivery-5d273',
    storageBucket: 'food-app-delivery-5d273.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX9KamsPdv6jdEfqu33Tirpf7WcQvP3hQ',
    appId: '1:266265608256:ios:6d383a8b518dad708f5fa5',
    messagingSenderId: '266265608256',
    projectId: 'food-app-delivery-5d273',
    storageBucket: 'food-app-delivery-5d273.appspot.com',
    iosBundleId: 'com.example.foodAppDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX9KamsPdv6jdEfqu33Tirpf7WcQvP3hQ',
    appId: '1:266265608256:ios:6d383a8b518dad708f5fa5',
    messagingSenderId: '266265608256',
    projectId: 'food-app-delivery-5d273',
    storageBucket: 'food-app-delivery-5d273.appspot.com',
    iosBundleId: 'com.example.foodAppDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABE_XNzPxTo5EHF_v5QUwJBVLdkFRdW6w',
    appId: '1:266265608256:web:918af08c06b692338f5fa5',
    messagingSenderId: '266265608256',
    projectId: 'food-app-delivery-5d273',
    authDomain: 'food-app-delivery-5d273.firebaseapp.com',
    storageBucket: 'food-app-delivery-5d273.appspot.com',
  );

}